// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Player struct {
	ID        int32
	UserID    int32
	Name      string
	BestScore int32
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
}
